version: '3.9'
services:
  # Servicio de base de datos disagro_hr_postgres
  postgres:
    image: postgres:17-alpine
    container_name: disagro_hr_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos para disagro_hr_test
      - ./db/ddl:/docker-entrypoint-initdb.d # Ejecución inicial para disagro_hr_test
    restart: always
    healthcheck: #Verificación de disponibilidad disagro_hr_test
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] 
      interval: 5s
      timeout: 5s
      retries: 5
  # Servicio ETL
  etl:
    build:
      context: ./etl 
      dockerfile: Dockerfile
    container_name: disagro_hr_etl
    environment:
      BIGQUERY_PROJECT_ID: "disagro-hr-test"
      GOOGLE_APPLICATION_CREDENTIALS: /app/bigquery_key.json
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    # Este contenedor solo se ejecuta una vez (Job)
    restart: "no"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: disagro_hr_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ./api:/app
    - ./tests/api:/app/tests
    restart: unless-stopped

volumes:
  postgres_data: